[project]
name = "green-ops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dsitweed", email = "luffy3042001@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.4.0",
    "langchain-classic>=1.0.8",
    "langchain-openai>=1.6.2",
    "mcp>=0.9.1,<1",
    "python-dotenv>=1.0.0",
]
